services:
  website:
    image: nginx:latest
    ports: 
      - '8080:80'
    volumes:
      - ./siteContent/pages:/usr/share/nginx/html:ro
      - ./siteContent/artRes:usr/share/nginx/html
      - ./siteContent/backend:usr/share/nginx/html
      - ./siteContent/cssFiles:usr/share/nginx/html

# ONLY WORKED WHEN ALL FILES IN ONE FOLDER, NEED TO FIND SOLUTION

# Start the development server in the background
#docker compose up -d

# View logs
#docker compose logs -f website

# Stop when done
#docker compose down

#https://oneuptime.com/blog/post/2026-02-08-how-to-create-a-dockerfile-for-a-static-website/view#adding-health-checks
