services:
  website:
    image: nginx:latest
    ports: 
      - '7272:80'
    volumes:
      - ./:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      crimeDB:
        condition: service_healthy # only run when database is available https://www.warp.dev/terminus/docker-compose-depends-on

  backend:
    image: node:26
    ports:
      - '8888:8888'
    user: 'node'
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    networks:
      - postgres-network
    command: ['npm', 'start']
    depends_on: # start database first before backend
      crimeDB:
        condition: service_healthy # only run when database is available https://www.warp.dev/terminus/docker-compose-depends-on

  crimeDB:
    image: postgres:18
    healthcheck: # ensure that database is available
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always
    container_name: database
    environment:
      - POSTGRES_PASSWORD=${crimePW}
      - POSTGRES_USER=${crimeUSER}
      - POSTGRES_DB=${crimeDBname}
    volumes:
      - ./pgdata:/docker-entrypoint-initdb.d/ # initialise database data using initialData.sql
    ports:
      - 5432:5432
    networks:
      - postgres-network
  
  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
    environment:
      ADMINER_DEFAULT_SERVER: crimeDB
    networks:
      - postgres-network
    depends_on:
      - crimeDB

networks:
  postgres-network:
    driver: bridge

#volumes:
#  dbData:
#volumes: 
#      - dbData:/var/lib/postgresql # for persistent data

# used volumes to seed data instead of dockerfile https://github.com/docker-library/postgres/issues/1373
# for connecting adminer to postgres https://dev.to/rafi021/set-up-postgresql-and-adminer-using-docker-for-local-web-development-104m
#https://www.docker.com/blog/how-to-use-the-postgres-docker-official-image/
# for multiple db in future https://stackoverflow.com/questions/46668233/multiple-databases-in-docker-and-docker-compose
# used .env instead of env_file. reason -> https://stackoverflow.com/questions/29377853/how-can-i-use-environment-variables-in-docker-compose

# to mount the whole project, made a nginx congif file to point to index.html
# do not need an EXPOSE or CMD line. these are included in the base nginx image and my image will inherit these

# TO RUN:
# Start the development server in the background
#docker compose up -d

# View logs
#docker compose logs -f website

# Stop when done
#docker compose down

# DB idea:
# countries. hover over and click to display customers -> second database could be orders
