server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html/siteContent/pages;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}

# https://medium.com/@wawerumwaura/nginx-and-docker-configuration-aac7b26210fe